name: CI with Earthly

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  build_id: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.7.10
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
      - name: Read VERSION file
        id: getversion
        run: echo "::set-output name=version::$(cat VERSION)"
      - name: Run build
        # run: earthly --verbose --build-arg VERSION=${{ steps.version.outputs.version }} --build-arg BUILD_NUMBER=${{ env.build_id }} --org leonard.audibert --sat my-satellite --ci --push +build
        run: earthly --verbose --build-arg VERSION=${{ steps.version.outputs.version }} --build-arg BUILD_NUMBER=${{ env.build_id }} --org leonard.audibert --ci --push +build
      - name: List Docker images
        run: docker images
