name: chatbond
description: Spark Meaningful Conversations
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.0.0"
  flutter: 3.7.0

dependencies:
  auto_route: ^7.8.0
  avatars: ^3.0.2
  bloc: ^8.1.2
  bubble: ^1.2.1
  bubble_tab_indicator: "^0.1.5"
  centrifuge: ^0.11.0
  chatbond_api:
    path: packages/chatbond_api
  easy_localization: ^3.0.1
  easy_localization_loader: ^1.0.1+1
  equatable: ^2.0.3
  firebase_core: ^2.13.0
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_types: ^3.6.0
  flutter_chat_ui: ^1.6.6
  flutter_dotenv: ^5.0.2
  flutter_form_bloc: ^0.30.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.17+2
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  font_awesome_flutter: ^10.4.0
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http_interceptor: ^1.0.2
  hydrated_bloc: ^9.1.1
  image_picker: ^1.0.2
  intl: ^0.18.1
  json_annotation: ^4.8.0
  loggy: ^2.0.2
  onesignal_flutter: ^5.0.0
  path_provider: ^2.0.13
  provider: ^6.0.5
  responsive_framework: ^1.1.0
  rxdart: ^0.27.7
  salomon_bottom_bar: ^3.3.2
  sentry_flutter: ^7.9.0
  share_plus: ^7.0.2
  sidebarx: ^0.16.1
  swipable_stack: ^2.0.0
  universal_html: ^2.2.4

dependency_overrides:
  intl: ^0.18.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  bloc_test: ^9.1.3
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1
  widgetbook: ^3.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env.development
    - envproduction
    - assets/translations/
    - assets/images/chatbond/
    - assets/images/
