# Generated by Django 3.2 on 2023-05-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionlikedevent",
            name="interlocutor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions_liked_events",
                to="chats.interlocutor",
            ),
            preserve_default=False,
        ),
    ]
