# Generated by Django 3.2 on 2023-05-12 03:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_alter_questionchat_status"),
        ("questions", "0002_questionlikedevent_interlocutor"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_questions",
                to="chats.interlocutor",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("A", "Approved"),
                    ("R", "Rejected"),
                    ("V", "Private"),
                ],
                default="P",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="questionlikedevent",
            name="status",
            field=models.CharField(
                choices=[("L", "Liked"), ("U", "Unliked")], default="L", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="content",
            field=models.TextField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="questionlikedevent",
            unique_together={("interlocutor", "question")},
        ),
        migrations.CreateModel(
            name="QuestionStatusChangeEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("A", "Approved"),
                            ("R", "Rejected"),
                            ("V", "Private"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="question_status_changes",
                        to="chats.interlocutor",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_changes",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="questionlikedevent",
            name="liked",
        ),
        migrations.CreateModel(
            name="QuestionFavoriteEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "interlocutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions_favorited_by",
                        to="chats.interlocutor",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_questions_events",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("interlocutor", "question")},
            },
        ),
    ]
