# Generated by Django 3.2 on 2023-05-27 13:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0003_historicalquestionchat"),
        ("questions", "0006_auto_20230521_1720"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionFeed",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("consumedAt", models.DateTimeField(default=None, null=True)),
                (
                    "interlocutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chats.interlocutor",
                    ),
                ),
                ("questions", models.ManyToManyField(to="questions.Question")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
