# Generated by Django 3.2 on 2023-06-18 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0003_historicalquestionchat"),
        ("questions", "0007_questionfeed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionfeed",
            name="interlocutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed",
                to="chats.interlocutor",
            ),
        ),
        migrations.AlterField(
            model_name="questionfeed",
            name="questions",
            field=models.ManyToManyField(related_name="feeds", to="questions.Question"),
        ),
    ]
