# Generated by Django 3.2 on 2023-09-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0009_auto_20230628_2041"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalquestion",
            name="external_unique_id",
            field=models.UUIDField(blank=None, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="external_unique_id",
            field=models.UUIDField(blank=None, null=True),
        ),
    ]
