# Generated by Django 3.2 on 2023-09-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0010_auto_20230905_1805"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquestion",
            name="external_unique_id",
            field=models.UUIDField(blank=None, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="external_unique_id",
            field=models.UUIDField(blank=None, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                condition=models.Q(external_unique_id__isnull=False),
                fields=("external_unique_id",),
                name="unique_external_id",
            ),
        ),
    ]
