# Generated by Django 3.2 on 2023-10-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_auto_20230906_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritedquestion',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalfavouritedquestion',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
