# Generated by Django 3.2 on 2023-10-09 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20231004_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchedStrings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('searched_string', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
