site_name: chatbond
site_description: Rekindle Relationships and Spark Meaningful Conversations.
repo_url: https://github.com/leomorpho/chatbond-api
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/leomorpho">leomorpho</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
