# Generated by Django 3.2 on 2023-05-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionchat",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("deleted", "Deleted"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
    ]
