# Generated by Django 3.2 on 2023-07-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0009_auto_20230628_2041"),
        ("chats", "0003_historicalquestionchat"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftquestionthread",
            name="published_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="draftquestionthread",
            name="question_thread",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="draft",
                to="chats.questionthread",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="draftquestionthread",
            unique_together={("chat_thread", "question", "drafter")},
        ),
        migrations.AlterUniqueTogether(
            name="questionthread",
            unique_together={("chat_thread", "question")},
        ),
    ]
