# Generated by Django 3.2 on 2023-07-07 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0004_auto_20230707_1445"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionthread",
            name="all_interlocutors_answered",
            field=models.BooleanField(default=False),
        ),
    ]
