name: chatbond_api
description: API to the chatbond backend.
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dev_dependencies:
  json_serializable: ^6.6.1
  test: ^1.24.2
  very_good_analysis: ^5.0.0+1

dependencies:
  build_runner: ^2.3.3
  centrifuge: ^0.11.0
  equatable: ^2.0.5
  flutter_chat_types: ^3.6.0
  flutter_chat_ui: ^1.6.6
  http: ^0.13.3
  http_interceptor: ^1.0.2
  json_annotation: ^4.8.0
  loggy: ^2.0.2
  mocktail: ^1.0.0
